# Generated by Django 3.2 on 2021-06-24 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Valve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('valve_name', models.CharField(blank=True, default='', max_length=50)),
                ('usb_port', models.CharField(choices=[('/dev/ttyUSB0', 'USB Port 0'), ('/dev/ttyUSB1', 'USB Port 1'), ('/dev/ttyUSB2', 'USB Port 2'), ('/dev/ttyUSB3', 'USB Port 3')], default='/dev/ttyUSB0', max_length=50)),
                ('pin', models.IntegerField()),
            ],
            options={
                'ordering': ['valve_name'],
            },
        ),
    ]
