# Generated by Django 3.2 on 2021-04-30 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('sensor_name', models.CharField(blank=True, default='', max_length=50)),
                ('sensor_type', models.CharField(choices=[('DHT11', 'DHT11 - Humidity/Temperature')], default='DHT11', max_length=50)),
                ('pin', models.IntegerField()),
            ],
            options={
                'ordering': ['sensor_name'],
            },
        ),
    ]
