# Generated by Django 3.2 on 2021-07-08 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0003_alter_sensor_sensor_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='in_use',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading', models.JSONField()),
                ('time_of_reading', models.DateTimeField(auto_now_add=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sensors.sensor')),
            ],
        ),
    ]
