# Generated by Django 3.2 on 2021-12-20 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0004_auto_20210708_0450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='usb_port',
            field=models.CharField(choices=[('/dev/bus/usb/1/4', 'Arduino MEGA')], default='/dev/bus/usb/1/4', max_length=50),
        ),
    ]
