# Generated by Django 3.2 on 2021-12-21 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0005_alter_sensor_usb_port'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='usb_port',
            field=models.CharField(choices=[('com3', 'Arduino MEGA'), ('/dev/ttyUSB1', 'USB1'), ('/dev/ttyUSB2', 'USB2'), ('/dev/ttyUSB3', 'USB3')], default='com3', max_length=50),
        ),
    ]
