# Generated by Django 3.2 on 2022-04-24 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0007_alter_sensor_usb_port'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='sensor_type',
            field=models.CharField(choices=[('DHT11', 'DHT11 - Humidity/Temperature'), ('Rain', 'Rain Sensor'), ('SoilSensor', 'Soil Sensor')], default='DHT11', max_length=50),
        ),
    ]
