# Generated by Django 3.2 on 2021-05-02 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='usb_port',
            field=models.CharField(choices=[('/dev/ttyUSB0', 'USB Port 0'), ('/dev/ttyUSB1', 'USB Port 1'), ('/dev/ttyUSB2', 'USB Port 2'), ('/dev/ttyUSB3', 'USB Port 3')], default='/dev/ttyUSB0', max_length=50),
        ),
    ]
